# Generated by Django 4.2 on 2023-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='sobreNome',
            new_name='sobrenome',
        ),
    ]
